# Generated by Django 3.2.5 on 2022-11-18 02:46

import core.helpers
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Locale',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title_zh', models.CharField(blank=True, default='', max_length=255, null=True, verbose_name='繁體中文')),
                ('title_en', models.CharField(blank=True, default='', max_length=255, null=True, verbose_name='英文')),
            ],
            options={
                'verbose_name': '欄位多語系',
                'verbose_name_plural': '欄位多語系',
            },
        ),
        migrations.CreateModel(
            name='LocaleSetting',
            fields=[
                ('id', models.CharField(max_length=10, primary_key=True, serialize=False, verbose_name='語言代碼')),
                ('language', models.CharField(max_length=50, verbose_name='系統語言')),
            ],
            options={
                'verbose_name': '翻譯對照表',
                'verbose_name_plural': '翻譯對照表',
            },
        ),
        migrations.CreateModel(
            name='Setting',
            fields=[
                ('id', models.CharField(max_length=10, primary_key=True, serialize=False, verbose_name='語言代碼')),
                ('language', models.CharField(max_length=50, verbose_name='系統語言')),
                ('sitename', models.CharField(blank=True, default='', max_length=100, null=True, verbose_name='系統名稱')),
                ('phone', models.CharField(blank=True, default='', max_length=100, null=True, verbose_name='電話')),
                ('logo', models.FileField(blank=True, null=True, upload_to=core.helpers.upload_handle, verbose_name='logo 圖片')),
                ('favicon', models.FileField(blank=True, null=True, upload_to=core.helpers.upload_handle, verbose_name='favicon 圖片')),
                ('style', models.FileField(blank=True, null=True, upload_to=core.helpers.upload_handle, verbose_name='CSS樣式')),
                ('detail_template', models.CharField(choices=[('Template-1', '版型一'), ('Template-2', '版型二')], default='Template-1', max_length=100, verbose_name='詳細頁面版型')),
                ('facebook', models.CharField(blank=True, default='', max_length=100, null=True, verbose_name='Facebook 連結')),
                ('instagram', models.CharField(blank=True, default='', max_length=100, null=True, verbose_name='Instagram 連結')),
                ('twitter', models.CharField(blank=True, default='', max_length=100, null=True, verbose_name='Twitter 連結')),
            ],
            options={
                'verbose_name': '網站設定',
                'verbose_name_plural': '網站設定',
            },
        ),
        migrations.CreateModel(
            name='TranslateSetting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('raw_string', models.CharField(max_length=255, verbose_name='原始文字')),
                ('translated_string', models.CharField(blank=True, default='', max_length=255, null=True, verbose_name='翻譯後文字')),
                ('locale', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='translatesetting_set', to='core.localesetting')),
            ],
            options={
                'verbose_name': '翻譯文字',
                'verbose_name_plural': '翻譯文字',
                'ordering': ['raw_string'],
            },
        ),
    ]
